development:
  adapter: postgresql
  encoding: unicode
  database: sportshub_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sportshub_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sportshub_production
  pool: 5
  username: postgres
  password:
