development:
  adapter: postgresql
  encoding: unicode
  database: sportive_diary_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sportive_diary_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sportive_diary_production
  pool: 5
  username: postgres
  password:
