# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Drill.create!(:name => "Throw & Catch", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Balance & Catch", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Ground Balls To", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Ground Balls Away", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Quickstick", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Throw & Cradle", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Throw & Shoot", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "One Hand", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Ab Crunch Machine", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Ab Roller", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Adductor", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Advanced Kettlebell Windmill", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Air Bike", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Arm Circles", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Around The Worlds", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Axle Deadlift", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Balance Board", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Band Hip Adductions", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Barbell Curl", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Barbell Deadlift", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Barbell Lunge", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Bench Jump", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Bench Sprint", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Bench Press - Powerlifting", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Bent Press", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Body Tricep Press", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Body-Up", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Bottoms Up", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Butterfly", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Cable Crossover", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Calf Press", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Calf Stretch Elbows Against Wall", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Carioca Quick Step", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Cat Stretch", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Chest And Front Of Shoulder Stretch", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Clean Deadlift", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "World's Greatest Stretch", :repetitions => 5, :plan_id => 0)
Drill.create!(:name => "Windmills", :repetitions => 5, :plan_id => 0)